# build env
FROM node:13.13-alpine as build
WORKDIR /app
COPY ./client/package*.json ./
COPY ./.env.prod ./
RUN mv ./.env.prod ./.env
RUN npm ci
COPY ./client/ ./
RUN npm run build

# production env
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE ${HUB_PORT:-80}
CMD ["nginx", "-g", "daemon off;"]