version: '3.7'
services:
  ldap:
    image: tovawr/openldap:withdata
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"
    env_file:
      - prod.env
#    ctfd:
#      image: ctfd/ctfd:latest
#      container_name: ctfd
#      ports:
#        - "8000:8000"
#    hub:
#      image: tovawr/dicystech-hub
#      container_name: hub
#      ports:
#        - "18000:3000"

