version: '3.7'
services:
  ldap:
    image: tovawr/openldap:0.1
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"
    env_file:
      - prod.env
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

#    ctfd:
#      image: ctfd/ctfd:latest
#      container_name: ctfd
#      ports:
#        - "8000:8000"
#    hub:
#      image: tovawr/dicystech-hub
#      container_name: hub
#      ports:
#        - "18000:3000"

volumes:
  ldap_data:
  ldap_config:

