version: '3.7'
services:
  hub:
    build:
      dockerfile: Dockerfile-hub
      context: ./hub
    container_name: hub
    env_file:
      - .env.prod
    ports:
      - "${HUB_PORT}:${HUB_PORT}"
    network_mode: host
  client:
    build:
      dockerfile: ./client/Dockerfile-client
      context: ./ # so the .env.prod file can be used by React
    container_name: client
    env_file:
      - .env.prod # enabled to apply CLIENT_PORT var to Dockerfile-client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"

  mongo:
    image: mongo:4.4.6
    container_name: mongo
    ports:
      - "${DB_PORT}:${DB_PORT}"
      
#  ldap:
#    image: tovawr/openldap:0.1
#    container_name: openldap
#    ports:
#      - "389:389"
#      - "636:636"
#    env_file:
#      - .env.prod
#    volumes:
#      - ldap_data:/var/lib/ldap
#      - ldap_config:/etc/ldap/slapd.d

#volumes:
#  ldap_data:
#  ldap_config:

