# build command:
# docker build -t tovawr/dicystech-hub .
FROM node:16.13-alpine

WORKDIR /app

COPY ./hub/package*.json ./
RUN npm install #--production
RUN npm audit fix

ENV ENV="production"
EXPOSE 3000

CMD ["npm","start"]
