version: '3.7'
services:
  hub:
    build:
      dockerfile: Dockerfile-hub
      context: ./hub
    container_name: hub
    env_file:
      - .env.prod
    ports:
      - "${HUB_PORT:-5000}:${HUB_PORT:-5000}"
  client:
    build:
      dockerfile: ./client/Dockerfile-client
      context: ./ # so the env file can be used
    #env_file:
    #  - .env.prod
    container_name: client
    ports:
      - "${CLIENT_PORT:-80}:${CLIENT_PORT:-80}"

  mongo:
    image: mongo:4.4.6
    container_name: mongo
    ports:
      - "${DB_PORT:-27017}:${DB_PORT:-27017}"
      
#  ldap:
#    image: tovawr/openldap:0.1
#    container_name: openldap
#    ports:
#      - "389:389"
#      - "636:636"
#    env_file:
#      - .env.prod
#    volumes:
#      - ldap_data:/var/lib/ldap
#      - ldap_config:/etc/ldap/slapd.d

#volumes:
#  ldap_data:
#  ldap_config:

