export const labCountries = [
  'Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi',
  'Cameroon', 'Cape Verde', 'Central African Republic', 'Chad', 'Comoros', 'Congo',
  'Democratic Republic of the Congo', 'Djibouti', 'Egypt', 'Eritrea', 'Ethiopia', 'Equatorial Guinea',
  'Eswatini', 'Gabon', 'The Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau',
  'Ivory Coast', 'Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar',
  'Malawi', 'Mali', 'Mauritania', 'Mauritius', 'Mozambique', 'Namibia',
  'Niger', 'Nigeria', 'Rwanda', 'Senegal', 'Seychelles', 'Sierra Leone',
  'Somalia', 'Somaliland', 'South Sudan', 'Sudan', 'South Africa', 'Tanzania',
  'Togo', 'Tunisia', 'Uganda', 'Zambia', 'Zimbabwe', 'Caribbean',
  'Antigua and Barbuda', 'Barbados', 'Cayman Islands', 'Cuba', 'Dominica', 'Dominican Republic',
  'Haiti', 'Jamaica', 'St. Vincent and the Grenadines', 'Trinidad and Tobago', 'Belize', 'Costa Rica',
  'El Salvador', 'Guatemala', 'Honduras', 'Nicaragua', 'Panama', 'Canada',
  'Mexico', 'United States', 'Argentina', 'Bolivia', 'Brazil', 'Chile',
  'Colombia', 'Ecuador', 'Guyana', 'Paraguay', 'Peru', 'Suriname',
  'Uruguay', 'Venezuela', 'Afghanistan', 'Bahrain', 'Bangladesh', 'Bhutan',
  'Brunei', 'Cambodia', 'China (mainland)', 'East Timor', 'Hong Kong', 'India',
  'Indonesia', 'Iran', 'Iraq', 'Israel', 'Japan', 'Jordan',
  'Kazakhstan', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Lebanon', 'Malaysia',
  'Macau', 'Mongolia', 'Myanmar', 'Nepal', 'North Korea', 'Oman',
  'Pakistan', 'Palestine', 'Philippines', 'Qatar', 'Saudi Arabia', 'Singapore',
  'South Korea', 'Sri Lanka', 'Syria', 'Taiwan', 'Tajikistan', 'Thailand',
  'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen', 'Albania',
  'Andorra', 'Armenia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium',
  'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark',
  'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Gibraltar',
  'Greece', 'Greenland', 'Hungary', 'Iceland', 'Ireland', 'Italy',
  'Kosovo', 'Latvia', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Malta',
  'Moldova', 'Monaco', 'Montenegro', 'Netherlands', 'Northern Cyprus', 'North Macedonia',
  'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'San Marino',
  'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland',
  'Turkey', 'Ukraine', 'United Kingdom', 'Vatican City', 'Australia', 'Cook Islands',
  'Fiji', 'French Polynesia', 'New Zealand', 'Nauru', 'Niue', 'Papua New Guinea',
  'Samoa', 'Solomon Islands', 'Tokelau', 'Tonga', 'Tuvalu', 'Vanuatu', 'Wallis and Futuna',
].sort();

export const robotComponents = ['LED', 'LCD Display', 'Temperature Sensor', 'Servomotor',
  'Infrared (IR) Sensor', 'Buzzer', 'Potentiometer', 'Light Sensor'];